<?php

namespace Gema\ArchivadorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**   
 * ArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoRepository extends EntityRepository
{
    	public function buscar($texto){
		
		$qb = $this->createQueryBuilder('a')
				->select('a')
				->where("a.nombre LIKE :texto")
                                ->setParameter("texto", '%' . $texto . '%')
				;
			return $qb->getQuery()->getResult();
		
	}
    	public function buscarPorTags($tags){
		
		$arrayTags = split(" ", $tags);
		$qb = $this->createQueryBuilder('a')
				->select('a')
				->join('a.tag','tag');
				foreach ($tags as $tag) {
				    $qb->orWhere("tag.nombre LIKE :tag")
				    ->setParameter("tag", '%' . $tag . '%');

				}
				
				
			return $qb->getQuery()->getResult();
		
	}
        public function ultimos(){
		
		$qb = $this->createQueryBuilder('a')
				->select('a')
                                ->setMaxResults(5)
                                ->orderBy('a.id', "DESC");
				;
			return $qb->getQuery()->getResult();
		
	}
}
