<?php

namespace Gema\ArchivadorBundle\Entity;

use Doctrine\ORM\EntityRepository;
use \Doctrine\ORM\Query\Expr\Join;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
	public function buscarArchivosSinJoin($tags){
		
		$arrayTags = split(" ", $tags);
		var_dump($arrayTags);
		
		$qb = $this->createQueryBuilder('tag')
				->select('tag');
				foreach ($arrayTags as $tag) {
				    echo $tag;
				    $qb->orWhere("tag.nombre LIKE :tag")
				    ->setParameter("tag", '%' . $tag . '%');
				}
				
				
			return $qb->getQuery()->getResult();
		
	}
	public function buscarArchivos($tags){
		
		$arrayTags = split(" ", $tags);
		//var_dump($arrayTags);
		
		$qb = $this->createQueryBuilder('tag')
				->select('tag','ar')
				->join('tag.archivos','ar');
				foreach ($arrayTags as $tag) {
				    echo $tag;
				    $qb->orWhere("tag.nombre LIKE :tag")
				    ->setParameter("tag", '%' . $tag . '%');
				}		
				//$qb->groupBy("ar");

				


//				foreach ($arrayTags as $tag) {
//				    echo $tag;
//				    $qb->orWhere("tag.nombre LIKE :tag")
//				    ->setParameter("tag", '%' . $tag . '%');
//
//				}
				
				
			return $qb->getQuery()->getResult();
		
	}
	public function seleccionar($lista){
	         $lista_array = explode(' ', $lista);
		$qb = $this->createQueryBuilder('tag')
				->select('tag')                                
				->where("tag.nombre IN (:lista)")			
				->setParameter("lista", $lista_array);
				;
		return $qb->getQuery()->getResult();
		;
	}
	public function seleccionarJoined($lista){
	         $lista_array = explode(' ', $lista);
		$qb = $this->createQueryBuilder('tag')
				->select('tag')                 
				->join('tag.archivos','ar')
				->where("tag.nombre IN (:lista)")			
				->setParameter("lista", $lista_array);
				;
		return $qb->getQuery()->getResult();
		;
	}
}
